platform :ios, '8.0'

target 'ScrollViewAutoLayoutTests' do
  inhibit_all_warnings!
  link_with 'ScrollViewAutoLayoutTests'

  pod 'Specta', '~> 1.0'
  pod 'Expecta', '~> 1.0'
  pod 'KIF', '~> 3.3'
end